[package]
name = "byte"
version = "0.0.1"
authors = ["Japroz-Saini <sainijaproz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_v8 = "0.15.0"
